export const articles = [
  {
    id: 1,
    title: "OpenAI Unveils GPT-5: Multimodal Reasoning at Human Levels",
    excerpt: "The latest breakthrough brings unprecedented capabilities in reasoning, coding, and scientific discovery with native multimodal understanding.",
    category: "AI",
    date: "May 24, 2026",
    readTime: "8 min",
    gradient: "bg-gradient-to-br from-blue-600 to-violet-600",
    icon: "🤖",
  },
  {
    id: 2,
    title: "Apple M5 Chip: 3nm Architecture Redefines Mobile Computing",
    excerpt: "Benchmarks reveal the M5 Ultra delivers 40% better performance-per-watt, enabling all-day battery life for professional workloads.",
    category: "Hardware",
    date: "May 23, 2026",
    readTime: "6 min",
    gradient: "bg-gradient-to-br from-pink-500 to-rose-500",
    icon: "💻",
  },
  {
    id: 3,
    title: "Quantum-Resistant Encryption Standard Finalized by NIST",
    excerpt: "New post-quantum cryptographic algorithms are now mandatory for federal agencies, marking the quantum-safe internet era.",
    category: "Security",
    date: "May 22, 2026",
    readTime: "5 min",
    gradient: "bg-gradient-to-br from-cyan-500 to-blue-500",
    icon: "🔒",
  },
  {
    id: 4,
    title: "Linux Kernel 6.14 Brings Revolutionary Scheduling",
    excerpt: "The new scheduler reduces latency by 30% for gaming and real-time applications while improving power efficiency significantly.",
    category: "Software",
    date: "May 21, 2026",
    readTime: "7 min",
    gradient: "bg-gradient-to-br from-emerald-500 to-teal-500",
    icon: "⚙️",
  },
  {
    id: 5,
    title: "SpaceX Starship Completes First Orbital Refueling",
    excerpt: "The historic demonstration paves the way for NASA's Artemis lunar missions and brings Mars colonization timelines closer.",
    category: "Space",
    date: "May 20, 2026",
    readTime: "4 min",
    gradient: "bg-gradient-to-br from-orange-500 to-amber-500",
    icon: "🚀",
  },
  {
    id: 6,
    title: "Microsoft Copilot Studio: Build AI Agents Without Code",
    excerpt: "The visual builder allows enterprises to create autonomous AI agents that handle complex business workflows across systems.",
    category: "AI",
    date: "May 19, 2026",
    readTime: "6 min",
    gradient: "bg-gradient-to-br from-indigo-500 to-purple-500",
    icon: "🧠",
  },
];

export const tools = [
  {
    id: 1,
    name: "ChatGPT",
    description: "OpenAI's conversational AI for writing, coding, analysis, and creative tasks. The gold standard for general-purpose LLMs.",
    category: "Chatbot",
    url: "https://chat.openai.com",
    tags: ["LLM", "Writing", "Coding"],
    featured: true,
  },
  {
    id: 2,
    name: "Claude",
    description: "Anthropic's AI assistant with exceptional reasoning, long context windows, and document analysis capabilities.",
    category: "Chatbot",
    url: "https://claude.ai",
    tags: ["Analysis", "Research", "Long Context"],
    featured: true,
  },
  {
    id: 3,
    name: "Midjourney",
    description: "AI image generation tool known for artistic, high-quality visuals and creative concept art.",
    category: "Image",
    url: "https://www.midjourney.com",
    tags: ["Art", "Design", "Generative"],
  },
  {
    id: 4,
    name: "GitHub Copilot",
    description: "AI pair programmer that suggests code and entire functions in real-time inside your IDE.",
    category: "Code",
    url: "https://github.com/features/copilot",
    tags: ["IDE", "Autocomplete", "Developer"],
    featured: true,
  },
  {
    id: 5,
    name: "ElevenLabs",
    description: "Realistic text-to-speech and voice cloning platform for content creators and developers.",
    category: "Audio",
    url: "https://elevenlabs.io",
    tags: ["TTS", "Voice", "Cloning"],
  },
  {
    id: 6,
    name: "Runway ML",
    description: "AI video generation and editing suite for filmmakers, designers, and creative professionals.",
    category: "Video",
    url: "https://runwayml.com",
    tags: ["Video", "Editing", "Gen-3"],
  },
  {
    id: 7,
    name: "Perplexity",
    description: "AI-powered search engine that provides cited, real-time answers to complex queries.",
    category: "Research",
    url: "https://www.perplexity.ai",
    tags: ["Search", "Citations", "Real-time"],
  },
  {
    id: 8,
    name: "Cursor",
    description: "AI-first code editor built on VS Code with integrated chat, composer, and codebase understanding.",
    category: "Code",
    url: "https://cursor.sh",
    tags: ["Editor", "AI Coding", "IDE"],
  },
  {
    id: 9,
    name: "Stable Diffusion 3",
    description: "Open-source image generation model with excellent text rendering and photorealistic outputs.",
    category: "Image",
    url: "https://stability.ai",
    tags: ["Open Source", "Local", "Photorealistic"],
  },
  {
    id: 10,
    name: "Notion AI",
    description: "Integrated AI writing assistant inside Notion for notes, docs, wikis, and project management.",
    category: "Productivity",
    url: "https://www.notion.so",
    tags: ["Notes", "Wiki", "Writing"],
  },
  {
    id: 11,
    name: "Suno",
    description: "AI music generation that creates full songs with vocals, instruments, and lyrics from text prompts.",
    category: "Audio",
    url: "https://suno.com",
    tags: ["Music", "Generation", "Vocals"],
  },
  {
    id: 12,
    name: "Replicate",
    description: "Platform to run and fine-tune open-source AI models in the cloud via simple API.",
    category: "Developer",
    url: "https://replicate.com",
    tags: ["API", "Models", "Cloud"],
  },
];

export const categories = ["All", "Chatbot", "Image", "Code", "Audio", "Video", "Research", "Productivity", "Developer"];